---
- name: Copying the Wildfly archive to the remote server
  copy: src={{wildfly_zip_filename}} dest=/tmp/{{wildfly_zip_filename}}

- name: Creating the Wildfly installation folder
  file: path={{wildfly_install_path}} state=directory mode=0755

- name: Unzipping Wildfly
  unarchive: src=/tmp/{{wildfly_zip_filename}} dest={{wildfly_install_path}} copy=no

- name: Creating symbolic links for default and latest versions of Wildfly
  file:
    src={{wildfly_install_path}}/{{wildfly_name}}
    path={{wildfly_install_path}}/{{item}}
    state=link
    force=yes
  with_items:
    - default
    - latest

- name: Setting the Wildfly PUBLIC interface to any IP address
  replace:
     dest={{wildfly_install_path}}/{{wildfly_name}}/standalone/configuration/standalone.xml
     regexp='<inet-address value="\${jboss.bind.address:127.0.0.1}"/>'
     replace='<inet-address value="${jboss.bind.address:0.0.0.0}"/>'

- name: Setting the Wildfly MANAGEMENT interface to any IP address
  replace:
     dest={{wildfly_install_path}}/{{wildfly_name}}/standalone/configuration/standalone.xml
     regexp='<inet-address value="\${jboss.bind.address.management:127.0.0.1}"/>'
     replace='<inet-address value="${jboss.bind.address.management:0.0.0.0}"/>'

- name: Copying the configuration file to the remote server
  template: src=wildfly.conf.j2 dest={{wildfly_install_path}}/{{wildfly_name}}/bin/init.d/wildfly.conf

- name: Creating a symbolic link in /etc to the wildfly configuration file
  file: src={{wildfly_install_path}}/{{wildfly_name}}/bin/init.d/wildfly.conf dest=/etc/default/wildfly.conf state=link mode=0755

- name: Creating a management user
  command: "{{wildfly_install_path}}/{{wildfly_name}}/bin/add-user.sh {{jboss_admin_user}} {{jboss_admin_pwd}}"

- name: Creating a symbolic link in /etc/init.d to start the Widlfly service
  file: src={{wildfly_install_path}}/{{wildfly_name}}/bin/init.d/wildfly-init-redhat.sh dest=/etc/init.d/wildfly state=link mode=0755

- name: Creating the Wildfly group
  group: name={{jboss_group}} state=present

- name: Creating the Wildfly user
  user: name={{jboss_user}} group={{jboss_user}} state=present

- name: Changing owner of wildfly folders
  command: chown -R {{jboss_user}}:{{jboss_user}} {{wildfly_install_path}}/{{wildfly_name}}

- name: Installing Wildfly as service
  command: chkconfig --add /etc/init.d/wildfly